load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("//bazel/go:go_test.bzl", "go_test")

go_library(
    name = "dfbuilder",
    srcs = ["dfbuilder.go"],
    importpath = "go.skia.org/infra/perf/go/dfbuilder",
    visibility = ["//visibility:public"],
    deps = [
        "//go/metrics2",
        "//go/paramtools",
        "//go/query",
        "//go/skerr",
        "//go/sklog",
        "//go/timer",
        "//go/vec32",
        "//perf/go/dataframe",
        "//perf/go/git",
        "//perf/go/progress",
        "//perf/go/tracecache",
        "//perf/go/tracefilter",
        "//perf/go/tracesetbuilder",
        "//perf/go/tracestore",
        "//perf/go/types",
        "@io_opencensus_go//trace",
        "@org_golang_x_sync//errgroup",
    ],
)

go_test(
    name = "dfbuilder_test",
    srcs = ["dfbuilder_test.go"],
    data = ["//perf/migrations:cockroachdb"],
    embed = [":dfbuilder"],
    # Perf CockroachDB tests fail intermittently when running locally (i.e. not on RBE) due to tests
    # running in parallel against the same CockroachDB instance:
    #
    #     pq: relation "schema_lock" already exists
    #
    # This is not an issue on RBE because each test target starts its own emulator instance.
    #
    # https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes-tests
    flaky = True,
    deps = [
        "//go/cache/local",
        "//go/cache/mock",
        "//go/paramtools",
        "//go/query",
        "//go/sql/pool",
        "//go/testutils",
        "//perf/go/config",
        "//perf/go/dataframe",
        "//perf/go/git",
        "//perf/go/git/gittest",
        "//perf/go/progress",
        "//perf/go/sql/sqltest",
        "//perf/go/tracecache",
        "//perf/go/tracestore",
        "//perf/go/tracestore/mocks",
        "//perf/go/tracestore/sqltracestore",
        "//perf/go/types",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//mock",
        "@com_github_stretchr_testify//require",
    ],
)
