load("@rules_go//go:def.bzl", "go_library")
load("//bazel/go:go_test.bzl", "go_test")

go_library(
    name = "dfiter",
    srcs = ["dfiter.go"],
    importpath = "go.skia.org/infra/perf/go/dfiter",
    visibility = ["//visibility:public"],
    deps = [
        "//go/metrics2",
        "//go/now",
        "//go/query",
        "//go/skerr",
        "//go/sklog",
        "//perf/go/alerts",
        "//perf/go/config",
        "//perf/go/dataframe",
        "//perf/go/git",
        "//perf/go/progress",
        "//perf/go/types",
        "@io_opencensus_go//trace",
    ],
)

go_test(
    name = "dfiter_test",
    srcs = ["dfiter_test.go"],
    data = ["//perf/migrations:cockroachdb"],
    embed = [":dfiter"],
    # Perf CockroachDB tests fail intermittently when running locally (i.e. not on RBE) due to tests
    # running in parallel against the same CockroachDB instance:
    #
    #     pq: relation "schema_lock" already exists
    #
    # This is not an issue on RBE because each test target starts its own emulator instance.
    #
    # https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes-tests
    flaky = True,
    deps = [
        "//go/now",
        "//go/paramtools",
        "//go/query",
        "//perf/go/alerts",
        "//perf/go/config",
        "//perf/go/dataframe",
        "//perf/go/dfbuilder",
        "//perf/go/git",
        "//perf/go/git/gittest",
        "//perf/go/progress",
        "//perf/go/tracestore",
        "//perf/go/tracestore/sqltracestore",
        "//perf/go/types",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
